module.exports = function anonymous(locals, attrs, escape, rethrow, merge) {
attrs = attrs || jade.attrs; escape = escape || jade.escape; rethrow = rethrow || jade.rethrow; merge = merge || jade.merge;
var __jade = [{ lineno: 1, filename: "src/app/template/timepicker.jade" }];
try {
var buf = [];
with (locals || {}) {
var interp;
var __indent = [];
__jade.unshift({ lineno: 1, filename: __jade[0].filename });
__jade.unshift({ lineno: 1, filename: __jade[0].filename });
buf.push('\n<div class="front">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 2, filename: __jade[0].filename });
buf.push('\n  <button>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 2, filename: __jade[0].filename });
buf.push('Set ' + escape((interp = name) == null ? '' : interp) + '');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.unshift({ lineno: 3, filename: __jade[0].filename });
buf.push('<span>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 3, filename: __jade[0].filename });
buf.push(' ');
__jade.shift();
__jade.unshift({ lineno: 4, filename: __jade[0].filename });
 if (name != '')	{
__jade.shift();
__jade.unshift({ lineno: 5, filename: __jade[0].filename });
buf.push('' + escape((interp = name) == null ? '' : interp) + ':');
__jade.shift();
__jade.unshift({ lineno: 6, filename: __jade[0].filename });
 }
__jade.shift();
__jade.unshift({ lineno: 7, filename: __jade[0].filename });
buf.push('<span class="reltime">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 8, filename: __jade[0].filename });
buf.push('\n    <button>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 8, filename: __jade[0].filename });
buf.push('Change');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.shift();
buf.push('\n</div>');
__jade.shift();
__jade.unshift({ lineno: 9, filename: __jade[0].filename });
buf.push('\n<div class="back">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 11, filename: __jade[0].filename });
buf.push('\n  <form>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 11, filename: __jade[0].filename });
buf.push('\n    <input name="day" size="2"/>');
__jade.shift();
__jade.unshift({ lineno: 12, filename: __jade[0].filename });
buf.push('.');
__jade.shift();
__jade.unshift({ lineno: 13, filename: __jade[0].filename });
buf.push('\n    <input name="month" size="2"/>');
__jade.shift();
__jade.unshift({ lineno: 14, filename: __jade[0].filename });
buf.push('.');
__jade.shift();
__jade.unshift({ lineno: 15, filename: __jade[0].filename });
buf.push('\n    <input name="year" size="4"/>');
__jade.shift();
__jade.unshift({ lineno: 16, filename: __jade[0].filename });
buf.push('&nbsp;&nbsp;&nbsp;');
__jade.shift();
__jade.unshift({ lineno: 17, filename: __jade[0].filename });
buf.push('\n    <input name="hour" size="2"/>');
__jade.shift();
__jade.unshift({ lineno: 18, filename: __jade[0].filename });
buf.push(':');
__jade.shift();
__jade.unshift({ lineno: 19, filename: __jade[0].filename });
buf.push('\n    <input name="minute" size="2"/>');
__jade.shift();
__jade.unshift({ lineno: 20, filename: __jade[0].filename });
buf.push(':');
__jade.shift();
__jade.unshift({ lineno: 21, filename: __jade[0].filename });
buf.push('\n    <input name="second" size="2"/>');
__jade.shift();
__jade.shift();
buf.push('\n  </form>');
__jade.shift();
__jade.unshift({ lineno: 22, filename: __jade[0].filename });
buf.push('\n  <button>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 22, filename: __jade[0].filename });
buf.push('Abort');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.unshift({ lineno: 23, filename: __jade[0].filename });
buf.push('\n  <button name="delete">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 23, filename: __jade[0].filename });
buf.push('Delete ' + escape((interp = name) == null ? '' : interp) + '');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.unshift({ lineno: 24, filename: __jade[0].filename });
buf.push('\n  <button name="save">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 24, filename: __jade[0].filename });
buf.push('Save ' + escape((interp = name) == null ? '' : interp) + '');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.shift();
buf.push('\n</div>');
__jade.shift();
__jade.shift();
}
return buf.join("");
} catch (err) {
  rethrow(err, __jade[0].filename, __jade[0].lineno);
}
}