/*** Generated by streamline 0.4.6 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__tryCatch=__rt.__tryCatch,__construct=__rt.__construct; (function() {
  var crypto, hash, pg, util, __indexOf = ([].indexOf || function(item) {
    for (var i = 0, l = this.length; (i < l); i++) { if (((i in this) && (this[i] === item))) { return i }; }; return -1;
  }), __hasProp = { }.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) { child[key] = parent[key]; }; }; function ctor() { this.constructor = child; }; ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  pg = require("pg")["native"];

  crypto = require("crypto");

  util = require("libsecretarius").util;

  hash = function(key) {
    return crypto.createHash("md5").update(key).digest("base64"); };


  module.exports = function(connectionString) {
    var Inbox, Transaction, getClient, model, query, queryMany, queryNone, queryOne, _this = this;

    model = { };
    getClient = function(cb) {
      return pg.connect(connectionString, function(error, client, done) {
        return cb(error, {
          client: client,
          done: done }); }); };



    model.listen = function model_listen__1(channel, cb, _) { var client; var __frame = { name: "model_listen__1", line: 29 }; return __func(_, this, arguments, model_listen__1, 2, __frame, function __$model_listen__1() {

        return getClient(__cb(_, __frame, 2, 15, function ___(__0, __1) { client = __1.client;
          client.on("notification", cb);
          return _(null, client.query((("LISTEN " + channel) + ";"))); }, true)); }); };

    Transaction = (function() {

      function Transaction(_) { var _ref, _this, __this = this; var __frame = { name: "Transaction", line: 37 }; return __func(_, this, arguments, Transaction, 0, __frame, function __$Transaction() { _this = __this;


          __this.rollback = function __this_rollback__1(_) { var __arguments = arguments; var __frame = { name: "__this_rollback__1", line: 40 }; return __func(_, this, arguments, __this_rollback__1, 0, __frame, function __$__this_rollback__1() {
              return _(null, Transaction.prototype.rollback.apply(_this, __arguments)); }); };

          __this.commit = function __this_commit__2(_) { var __arguments = arguments; var __frame = { name: "__this_commit__2", line: 43 }; return __func(_, this, arguments, __this_commit__2, 0, __frame, function __$__this_commit__2() {
              return _(null, Transaction.prototype.commit.apply(_this, __arguments)); }); }; return (function __$Transaction(_) {

            return getClient(__cb(_, __frame, 9, 15, function ___(__0, __3) { _ref = __3; __this.client = _ref.client; return _(null, __this.done = _ref.done); }, true)); })(__cb(_, __frame, -36, 7, function __$Transaction() {
            return __this.client.query("begin", __cb(_, __frame, 10, 8, _, true)); }, true)); }); };


      Transaction.prototype.commit = function Transaction_prototype_commit__1(_) { var __this = this; var __frame = { name: "Transaction_prototype_commit__1", line: 50 }; return __func(_, this, arguments, Transaction_prototype_commit__1, 0, __frame, function __$Transaction_prototype_commit__1() {
          return __this.client.query("commit", __cb(_, __frame, 1, 8, function __$Transaction_prototype_commit__1() {
            return _(null, __this.done()); }, true)); }); };


      Transaction.prototype.rollback = function Transaction_prototype_rollback__2(_) { var __this = this; var __frame = { name: "Transaction_prototype_rollback__2", line: 55 }; return __func(_, this, arguments, Transaction_prototype_rollback__2, 0, __frame, function __$Transaction_prototype_rollback__2() {
          return __this.client.query("rollback", __cb(_, __frame, 1, 8, function __$Transaction_prototype_rollback__2() {
            return _(null, __this.done()); }, true)); }); };


      Transaction.prototype.queryMany = function Transaction_prototype_queryMany__3(_, config) { var __this = this; var __frame = { name: "Transaction_prototype_queryMany__3", line: 60 }; return __func(_, this, arguments, Transaction_prototype_queryMany__3, 0, __frame, function __$Transaction_prototype_queryMany__3() {
          config.name = hash(config.text);
          return __this.client.query(config, __cb(_, __frame, 2, 15, function ___(__0, __2) { var __1 = __2.rows; return _(null, __1); }, true)); }); };


      Transaction.prototype.queryOne = function Transaction_prototype_queryOne__4(_, config) { var __this = this; var __frame = { name: "Transaction_prototype_queryOne__4", line: 65 }; return __func(_, this, arguments, Transaction_prototype_queryOne__4, 0, __frame, function __$Transaction_prototype_queryOne__4() {
          return __this.queryMany(__cb(_, __frame, 1, 8, function __$Transaction_prototype_queryOne__4() {
            if ((res[0] == null)) {
              return _(new Error("queryOne got no result")); } ;

            return _(null, res[0]); }, true), config); }); };


      Transaction.prototype.queryNone = function Transaction_prototype_queryNone__5(_, config) { var __this = this; var __frame = { name: "Transaction_prototype_queryNone__5", line: 73 }; return __func(_, this, arguments, Transaction_prototype_queryNone__5, 0, __frame, function __$Transaction_prototype_queryNone__5() {
          return __this.queryMany(__cb(_, __frame, 1, 8, function __$Transaction_prototype_queryNone__5() {
            return _(null, null); }, true), config); }); };


      return Transaction;

    })();
    query = function query__2(_, config) { var res, t, transaction, __this = this; var __frame = { name: "query__2", line: 81 }; return __func(_, this, arguments, query__2, 0, __frame, function __$query__2() {

        transaction = config.transaction; return (function __$query__2(__then) {
          if ((transaction != null)) {
            t = transaction; __then(); } else {

            return __construct(Transaction, 0)(__cb(_, __frame, NaN, NaN, function ___(__0, __1) { t = __1; __then(); }, true)); } ; })(function __$query__2() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$query__2() { return (function __$query__2(__then) {


                  if ((config.before != null)) {
                    return config.before.call(__this, __cb(_, __frame, 10, 10, __then, true), config, t); } else { __then(); } ; })(function __$query__2() {

                  return t[config.func](__cb(_, __frame, 12, 14, function ___(__0, __2) { res = __2; return (function __$query__2(__then) {



                      if ((config.after != null)) {
                        return config.after.call(__this, __cb(_, __frame, 17, 17, function ___(__0, __3) { result(__3);
                          if (((typeof result !== "undefined") && (result !== null))) {
                            res = result; } ; __then(); }, true), res, t); } else { __then(); } ; })(function __$query__2() { return (function __$query__2(__then) {


                        if ((transaction == null)) {
                          return t.commit(__cb(_, __frame, 23, 10, __then, true)); } else { __then(); } ; })(__then); }); }, true), { text: config.text, values: ((config.values != null) ? config.values : []) }); }); }); })(function ___(error, __result) { __tryCatch(_, function __$query__2() { if (error) { return (function __$query__2(__then) {


                    if ((transaction == null)) {
                      return t.rollback(__cb(_, __frame, 27, 10, __then, true)); } else { __then(); } ; })(function __$query__2() {

                    return _(error); }); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, function __$query__2() {

              return _(null, res); }); }); }); }); };

    queryNone = function queryNone__3(_, transaction, config) { var __frame = { name: "queryNone__3", line: 114 }; return __func(_, this, arguments, queryNone__3, 0, __frame, function __$queryNone__3() {
        config.transaction = transaction;
        config.func = "queryNone";
        return query(__cb(_, __frame, 3, 13, _, true), config); }); };

    queryOne = function queryOne__4(_, transaction, config) { var __frame = { name: "queryOne__4", line: 119 }; return __func(_, this, arguments, queryOne__4, 0, __frame, function __$queryOne__4() {
        config.transaction = transaction;
        config.func = "queryOne";
        return query(__cb(_, __frame, 3, 13, _, true), config); }); };

    queryMany = function queryMany__5(_, transaction, config) { var __frame = { name: "queryMany__5", line: 124 }; return __func(_, this, arguments, queryMany__5, 0, __frame, function __$queryMany__5() {
        config.transaction = transaction;
        config.func = "queryMany";
        return query(__cb(_, __frame, 3, 13, _, true), config); }); };

    model.Information = (function() {

      function Information(id) {
        var tempType;
        this.id = id;
        tempType = this.constructor.name.toLowerCase();
        if ((tempType !== "information")) {
          this.type = tempType; } ; };



      Information.prototype.create = function Information_prototype_create__1(_, status, referencing, t) { var __frame = { name: "Information_prototype_create__1", line: 140 }; return __func(_, this, arguments, Information_prototype_create__1, 0, __frame, function __$Information_prototype_create__1() {
          if ((status == null)) {
            status = "default"; } ;

          if ((referencing == null)) {
            referencing = null; } ;

          return queryOne(__cb(_, __frame, 7, 15, _, true), t, {
            text: "INSERT INTO information (status) VALUES ($1) RETURNING id;",
            values: [status,],
            after: function after__1(_, res, t) { var __this = this; var __frame = { name: "after__1", line: 150 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {
                __this.id = res.id; return (function __$after__1(__then) {
                  if ((referencing != null)) {
                    return __this.addReference(__cb(_, __frame, 3, 14, __then, true), referencing, t); } else { __then(); } ; })(function __$after__1() {

                  return _(null, __this.id); }); }); } }); }); };




      Information.prototype.addReference = function Information_prototype_addReference__2(_, reference, t) { var __this = this; var __frame = { name: "Information_prototype_addReference__2", line: 160 }; return __func(_, this, arguments, Information_prototype_addReference__2, 0, __frame, function __$Information_prototype_addReference__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "INSERT INTO \"references\" (id, referenceid) VALUES ($1, $2);",
            values: [__this.id,reference,] }); }); };



      Information.prototype.removeReference = function Information_prototype_removeReference__3(_, reference, t) { var __this = this; var __frame = { name: "Information_prototype_removeReference__3", line: 167 }; return __func(_, this, arguments, Information_prototype_removeReference__3, 0, __frame, function __$Information_prototype_removeReference__3() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "DELETE FROM \"references\" WHERE id=$1 AND referenceid=$2",
            values: [__this.id,reference,] }); }); };



      Information.prototype.getType = function Information_prototype_getType__4(_, t) { var __this = this; var __frame = { name: "Information_prototype_getType__4", line: 174 }; return __func(_, this, arguments, Information_prototype_getType__4, 0, __frame, function __$Information_prototype_getType__4() {
          return __this.get(__cb(_, __frame, 1, 15, function ___(__0, __2) { var __1 = __2.type; return _(null, __1); }, true)); }); };


      Information.prototype.get = function Information_prototype_get__5(_, t) { var __this = this; var __frame = { name: "Information_prototype_get__5", line: 178 }; return __func(_, this, arguments, Information_prototype_get__5, 0, __frame, function __$Information_prototype_get__5() {
          return queryOne(__cb(_, __frame, 1, 15, _, true), t, {
            text: "SELECT getInformation($1) as info;",
            values: [__this.id,],
            after: function after__1(_, res, t) { var __frame = { name: "after__1", line: 182 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {
                return _(null, JSON.parse(res.info)); }); } }); }); };




      Information.prototype.setStatus = function Information_prototype_setStatus__6(_, status, t) { var __this = this; var __frame = { name: "Information_prototype_setStatus__6", line: 188 }; return __func(_, this, arguments, Information_prototype_setStatus__6, 0, __frame, function __$Information_prototype_setStatus__6() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE information SET status=$2 WHERE id=$1;",
            values: [__this.id,status,] }); }); };



      Information.prototype.setDelay = function Information_prototype_setDelay__7(_, delay, t) { var __this = this; var __frame = { name: "Information_prototype_setDelay__7", line: 195 }; return __func(_, this, arguments, Information_prototype_setDelay__7, 0, __frame, function __$Information_prototype_setDelay__7() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE information SET status='inbox', delay=$2 WHERE id=$1;",
            values: [__this.id,((delay != null) ? delay.toISOString() : null),] }); }); };



      Information.prototype.attach = function Information_prototype_attach__8(_, file, t) { var __this = this; var __frame = { name: "Information_prototype_attach__8", line: 202 }; return __func(_, this, arguments, Information_prototype_attach__8, 0, __frame, function __$Information_prototype_attach__8() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "INSERT INTO attachments (id, fileid) VALUES ($1, $2);",
            values: [__this.id,file,] }); }); };



      Information.prototype.detach = function Information_prototype_detach__9(_, file, t) { var __this = this; var __frame = { name: "Information_prototype_detach__9", line: 209 }; return __func(_, this, arguments, Information_prototype_detach__9, 0, __frame, function __$Information_prototype_detach__9() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "DELETE FROM attachments WHERE id=$1 AND fileid=$2);",
            values: [__this.id,file,] }); }); };



      Information.prototype._set = function Information_prototype__set__10(_, table, map, allowed, t) { var answers, future, key, value, _i, _len, __this = this; var __frame = { name: "Information_prototype__set__10", line: 216 }; return __func(_, this, arguments, Information_prototype__set__10, 0, __frame, function __$Information_prototype__set__10() {

          answers = [];
          for (key in map) {
            value = map[key];
            if ((((allowed == null)) || (__indexOf.call(allowed, key) >= 0))) {
              answers.push(queryNone(null, t, {
                text: (("UPDATE " + table) + " SET $2=$3 WHERE id=$1;"),
                values: [__this.id,key,value,] })); } ; };



          _i = 0; _len = answers.length; var __2 = false; return (function ___(__break) { var __more; var __loop = __cb(_, __frame, 0, 0, function __$Information_prototype__set__10() { __more = false; if (__2) { _i++; } else { __2 = true; } ; var __1 = (_i < _len); if (__1) {
                future = answers[_i];
                return future(__cb(_, __frame, 14, 10, function __$Information_prototype__set__10() { while (__more) { __loop(); }; __more = true; }, true)); } else { __break(); } ; }); do { __loop(); } while (__more); __more = true; })(function __$Information_prototype__set__10() {

            return _(null, null); }); }); };


      Information.prototype.getReferences = function Information_prototype_getReferences__11(_, t) { var __this = this; var __frame = { name: "Information_prototype_getReferences__11", line: 235 }; return __func(_, this, arguments, Information_prototype_getReferences__11, 0, __frame, function __$Information_prototype_getReferences__11() {
          return queryMany(__cb(_, __frame, 1, 15, _, true), t, {
            text: "SELECT referenceid FROM \"references\" WHERE id=$1;",
            values: [__this.id,],
            after: function after__1(_, res) { var row, _i, _len, _results; var __frame = { name: "after__1", line: 239 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {

                _results = [];
                for (_i = 0, _len = res.length; (_i < _len); _i++) {
                  row = res[_i];
                  _results.push(row.referenceid); };

                return _(null, _results); }); } }); }); };




      Information.prototype.getAttachments = function Information_prototype_getAttachments__12(_, t) { var __this = this; var __frame = { name: "Information_prototype_getAttachments__12", line: 251 }; return __func(_, this, arguments, Information_prototype_getAttachments__12, 0, __frame, function __$Information_prototype_getAttachments__12() {
          return queryMany(__cb(_, __frame, 1, 15, _, true), t, {
            text: "SELECT fileid FROM attachments WHERE id=$1;",
            values: [__this.id,],
            after: function after__1(_, res) { var row, _i, _len, _results; var __frame = { name: "after__1", line: 255 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {

                _results = [];
                for (_i = 0, _len = res.length; (_i < _len); _i++) {
                  row = res[_i];
                  _results.push(row.fileid); };

                return _(null, _results); }); } }); }); };




      Information.getAllIDs = function Information_getAllIDs__13(_, t) { var __this = this; var __frame = { name: "Information_getAllIDs__13", line: 267 }; return __func(_, this, arguments, Information_getAllIDs__13, 0, __frame, function __$Information_getAllIDs__13() {
          return queryOne(__cb(_, __frame, 1, 15, _, true), t, {
            text: (("select array_to_json(array_agg(id)) as list from " + (__this.name.toLowerCase())) + ";"),
            after: function after__1(_, res) { var __frame = { name: "after__1", line: 270 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {
                if ((res.list != null)) {
                  return _(null, JSON.parse(res.list)); }
                 else {
                  return _(null, []); } ; _(); }); } }); }); };





      Information.getAll = function Information_getAll__14(_, t) { var __this = this; var __frame = { name: "Information_getAll__14", line: 280 }; return __func(_, this, arguments, Information_getAll__14, 0, __frame, function __$Information_getAll__14() {
          return queryOne(__cb(_, __frame, 1, 15, _, true), t, {
            text: (("SELECT array_to_json(array_agg(getInformation(id))) as list FROM " + (__this.name.toLowerCase())) + ";"),
            after: function after__1(_, res) { var __frame = { name: "after__1", line: 283 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {
                if ((res.list != null)) {
                  return _(null, JSON.parse(res.list)); }
                 else {
                  return _(null, []); } ; _(); }); } }); }); };



























      return Information;

    })();
    model.Note = (function(_super) {

      __extends(Note, _super);

      function Note() {
        return Note.__super__.constructor.apply(this, arguments); };


      Note.prototype.create = function Note_prototype_create__1(_, content, t) { var _this, __this = this; var __frame = { name: "Note_prototype_create__1", line: 326 }; return __func(_, this, arguments, Note_prototype_create__1, 0, __frame, function __$Note_prototype_create__1() { _this = __this;

          return queryNone(__cb(_, __frame, 2, 15, _, true), t, {
            before: function before__1(_, config, t) { var __frame = { name: "before__1", line: 329 }; return __func(_, this, arguments, before__1, 0, __frame, function __$before__1() {
                return model.Information.prototype.create.call(_this, __cb(_, __frame, 1, 12, function __$before__1() {
                  return _(null, config.values = [_this.id,content,]); }, true), "inbox", null, t); }); },

            text: "INSERT INTO note (id, content) VALUES ($1, $2);",
            after: function after__2(_) { var __this = this; var __frame = { name: "after__2", line: 334 }; return __func(_, this, arguments, after__2, 0, __frame, function __$after__2() {
                return _(null, __this.id); }); } }); }); };




      Note.prototype.setContent = function Note_prototype_setContent__2(_, content, t) { var __this = this; var __frame = { name: "Note_prototype_setContent__2", line: 340 }; return __func(_, this, arguments, Note_prototype_setContent__2, 0, __frame, function __$Note_prototype_setContent__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE note SET content=$2 WHERE id=$1",
            values: [__this.id,content,] }); }); };



      return Note;

    })(model.Information);
    model.Task = (function(_super) {

      __extends(Task, _super);

      function Task() {
        return Task.__super__.constructor.apply(this, arguments); };


      Task.prototype.create = function Task_prototype_create__1(_, description, referencing, parent, t) { var __frame = { name: "Task_prototype_create__1", line: 358 }; return __func(_, this, arguments, Task_prototype_create__1, 0, __frame, function __$Task_prototype_create__1() {
          if ((referencing == null)) {
            referencing = null; } ;

          if ((parent == null)) {
            parent = null; } ;

          return queryNone(__cb(_, __frame, 7, 15, _, true), t, {
            before: function before__1(_, config, t) { var __this = this; var __frame = { name: "before__1", line: 366 }; return __func(_, this, arguments, before__1, 0, __frame, function __$before__1() {
                return model.Information.prototype.create.call(__this, __cb(_, __frame, 1, 12, function __$before__1() {
                  return _(null, config.values = [__this.id,description,parent,]); }, true), "default", referencing, t); }); },

            text: "INSERT INTO task (id, description, parent) VALUES ($1, $2, $3);",
            after: function after__2(_) { var __this = this; var __frame = { name: "after__2", line: 371 }; return __func(_, this, arguments, after__2, 0, __frame, function __$after__2() {
                return _(null, __this.id); }); } }); }); };




      Task.prototype.done = function Task_prototype_done__2(_, t) { var __this = this; var __frame = { name: "Task_prototype_done__2", line: 377 }; return __func(_, this, arguments, Task_prototype_done__2, 0, __frame, function __$Task_prototype_done__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE task SET completed=CURRENT_TIMESTAMP WHERE id=$1",
            values: [__this.id,] }); }); };



      Task.prototype.undo = function Task_prototype_undo__3(_, t) { var __this = this; var __frame = { name: "Task_prototype_undo__3", line: 384 }; return __func(_, this, arguments, Task_prototype_undo__3, 0, __frame, function __$Task_prototype_undo__3() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE task SET completed=NULL WHERE id=$1",
            values: [__this.id,] }); }); };



      Task.prototype.setParent = function Task_prototype_setParent__4(_, parent, t) { var __this = this; var __frame = { name: "Task_prototype_setParent__4", line: 391 }; return __func(_, this, arguments, Task_prototype_setParent__4, 0, __frame, function __$Task_prototype_setParent__4() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE task SET parent=$2 WHERE id=$1;",
            values: [__this.id,parent,] }); }); };



      Task.prototype.setDeadline = function Task_prototype_setDeadline__5(_, deadline, t) { var __this = this; var __frame = { name: "Task_prototype_setDeadline__5", line: 398 }; return __func(_, this, arguments, Task_prototype_setDeadline__5, 0, __frame, function __$Task_prototype_setDeadline__5() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE task SET deadline=$2 WHERE id=$1;",
            values: [__this.id,((deadline != null) ? deadline.toISOString() : null),] }); }); };



      Task.prototype.setDescription = function Task_prototype_setDescription__6(_, description, t) { var __this = this; var __frame = { name: "Task_prototype_setDescription__6", line: 405 }; return __func(_, this, arguments, Task_prototype_setDescription__6, 0, __frame, function __$Task_prototype_setDescription__6() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "update task set description=$2 where id=$1",
            values: [__this.id,description,] }); }); };



      return Task;

    })(model.Information);
    model.Project = (function(_super) {

      __extends(Project, _super);

      function Project() {
        return Project.__super__.constructor.apply(this, arguments); };


      Project.prototype.create = function Project_prototype_create__1(_, description, referencing, parent, t) { var _this, __this = this; var __frame = { name: "Project_prototype_create__1", line: 423 }; return __func(_, this, arguments, Project_prototype_create__1, 0, __frame, function __$Project_prototype_create__1() { _this = __this;

          if ((referencing == null)) {
            referencing = null; } ;

          if ((parent == null)) {
            parent = null; } ;

          return queryNone(__cb(_, __frame, 8, 15, _, true), t, {
            before: function before__1(_, config, t) { var __frame = { name: "before__1", line: 432 }; return __func(_, this, arguments, before__1, 0, __frame, function __$before__1() {
                return model.Task.prototype.create.call(_this, __cb(_, __frame, 1, 12, function __$before__1() {
                  return _(null, config.values = [_this.id,]); }, true), description, referencing, parent, t); }); },

            text: "INSERT INTO project (id) VALUES ($1);",
            after: function after__2(_) { var __this = this; var __frame = { name: "after__2", line: 437 }; return __func(_, this, arguments, after__2, 0, __frame, function __$after__2() {
                return _(null, __this.id); }); } }); }); };




      Project.prototype.collapse = function Project_prototype_collapse__2(_, t) { var __this = this; var __frame = { name: "Project_prototype_collapse__2", line: 443 }; return __func(_, this, arguments, Project_prototype_collapse__2, 0, __frame, function __$Project_prototype_collapse__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE project SET collapsed=TRUE WHERE id=$1;",
            values: [__this.id,] }); }); };



      Project.prototype.uncollapse = function Project_prototype_uncollapse__3(_, t) { var __this = this; var __frame = { name: "Project_prototype_uncollapse__3", line: 450 }; return __func(_, this, arguments, Project_prototype_uncollapse__3, 0, __frame, function __$Project_prototype_uncollapse__3() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE project SET collapsed=FALSE WHERE id=$1;",
            values: [__this.id,] }); }); };



      return Project;

    })(model.Task);
    model.Asap = (function(_super) {

      __extends(Asap, _super);

      function Asap() {
        return Asap.__super__.constructor.apply(this, arguments); };


      Asap.prototype.create = function Asap_prototype_create__1(_, description, list, referencing, project, t) { var __frame = { name: "Asap_prototype_create__1", line: 468 }; return __func(_, this, arguments, Asap_prototype_create__1, 0, __frame, function __$Asap_prototype_create__1() {
          if ((referencing == null)) {
            referencing = null; } ;

          if ((project == null)) {
            project = null; } ;

          return queryNone(__cb(_, __frame, 7, 15, _, true), t, {
            before: function before__1(_, config, t) { var __this = this; var __frame = { name: "before__1", line: 476 }; return __func(_, this, arguments, before__1, 0, __frame, function __$before__1() {
                return model.Task.prototype.create.call(__this, __cb(_, __frame, 1, 12, function __$before__1() {
                  return _(null, config.values = [__this.id,list,]); }, true), description, referencing, project, t); }); },

            text: "INSERT INTO asap (id, asaplist) VALUES ($1, $2);",
            after: function after__2(_) { var __this = this; var __frame = { name: "after__2", line: 481 }; return __func(_, this, arguments, after__2, 0, __frame, function __$after__2() {
                return _(null, __this.id); }); } }); }); };




      Asap.prototype.setList = function Asap_prototype_setList__2(_, list, t) { var __this = this; var __frame = { name: "Asap_prototype_setList__2", line: 487 }; return __func(_, this, arguments, Asap_prototype_setList__2, 0, __frame, function __$Asap_prototype_setList__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE asap SET asaplist=$2 WHERE id=$1;",
            values: [__this.id,list,] }); }); };



      return Asap;

    })(model.Task);
    model.AsapList = (function(_super) {

      __extends(AsapList, _super);

      function AsapList() {
        return AsapList.__super__.constructor.apply(this, arguments); };


      AsapList.prototype.create = function AsapList_prototype_create__1(_, name, t) { var __frame = { name: "AsapList_prototype_create__1", line: 505 }; return __func(_, this, arguments, AsapList_prototype_create__1, 0, __frame, function __$AsapList_prototype_create__1() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            before: function before__1(_, config, t) { var __this = this; var __frame = { name: "before__1", line: 507 }; return __func(_, this, arguments, before__1, 0, __frame, function __$before__1() {
                return model.Information.prototype.create.call(__this, __cb(_, __frame, 1, 12, function __$before__1() {
                  return _(null, config.values = [__this.id,name,]); }, true), "default", null, t); }); },

            text: "INSERT INTO asaplist (id, name) VALUES ($1, $2);",
            after: function after__2(_) { var __this = this; var __frame = { name: "after__2", line: 512 }; return __func(_, this, arguments, after__2, 0, __frame, function __$after__2() {
                return _(null, __this.id); }); } }); }); };




      AsapList.prototype.rename = function AsapList_prototype_rename__2(_, name, t) { var __this = this; var __frame = { name: "AsapList_prototype_rename__2", line: 518 }; return __func(_, this, arguments, AsapList_prototype_rename__2, 0, __frame, function __$AsapList_prototype_rename__2() {
          return queryNone(__cb(_, __frame, 1, 15, _, true), t, {
            text: "UPDATE asaplist SET name=$2 WHERE id=$1;",
            values: [__this.id,name,] }); }); };



























































































































































      return AsapList;

    })(model.Information);
    Inbox = (function() {

      function Inbox() {  };

      Inbox.prototype.getSize = function Inbox_prototype_getSize__1(_, t) { var __frame = { name: "Inbox_prototype_getSize__1", line: 684 }; return __func(_, this, arguments, Inbox_prototype_getSize__1, 0, __frame, function __$Inbox_prototype_getSize__1() {
          return queryOne(__cb(_, __frame, 1, 15, _, true), t, {
            text: "SELECT count(*) FROM inbox;",
            after: function after__1(_, res) { var __frame = { name: "after__1", line: 687 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {
                return _(null, res.count); }); } }); }); };




      Inbox.prototype.getFirst = function Inbox_prototype_getFirst__2(_, t) { var __frame = { name: "Inbox_prototype_getFirst__2", line: 693 }; return __func(_, this, arguments, Inbox_prototype_getFirst__2, 0, __frame, function __$Inbox_prototype_getFirst__2() {
          return queryMany(__cb(_, __frame, 1, 15, _, true), t, {
            text: "SELECT id FROM inbox ORDER BY \"createdAt\" LIMIT 1;",
            after: function after__1(_, res) { var _ref; var __frame = { name: "after__1", line: 696 }; return __func(_, this, arguments, after__1, 0, __frame, function __$after__1() {

                return _(null, (((_ref = res[0]) != null) ? _ref.id : void 0)); }); } }); }); };




      Inbox.prototype.get = function Inbox_prototype_get__3(_, t) { var first, size, __this = this; var __frame = { name: "Inbox_prototype_get__3", line: 703 }; return __func(_, this, arguments, Inbox_prototype_get__3, 0, __frame, function __$Inbox_prototype_get__3() {

          return __this.getSize(__cb(_, __frame, 2, 15, function ___(__0, __1) { size = __1;
            return __this.getFirst(__cb(_, __frame, 3, 16, function ___(__0, __2) { first = __2;

              return size(__cb(_, __frame, 5, 16, function ___(__0, __4) {
                return first(__cb(_, __frame, 6, 17, function ___(__0, __5) { var __3 = { size: __4, first: __5 }; return _(null, __3); }, true)); }, true)); }, true), t); }, true), t); }); };



      return Inbox;

    })();








    model.inbox = new Inbox;
    return model; };


}).call(this);