/*** Generated by streamline 0.4.6 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename); (function() {
  var request, sec, ui, util, _ref;

  ui = require("./ui");

  sec = require("libsecretarius");

  util = sec.util;

  window.model = sec();

  request = (((_ref = document.URL.match(/https?:\/\/.*\/(.*)/)) != null) ? _ref[1] : void 0);

  $(function() {
    return new ui.slots.WindowSlot(util.dummy, request); });


}).call(this);